####创建数组####

In [30]:
import numpy as np

detal=[1,2,3,4]
w3=np.array(detal)
print(w3)

[1 2 3 4]


In [31]:
array1=np.arange(10)
print(array1)

array2=np.arange(0,1,0.2)
print(array2)

array3=np.linspace(0,1,5)
print(array3)

array4=np.logspace(0,1,5)
print(array4)

[0 1 2 3 4 5 6 7 8 9]
[0.  0.2 0.4 0.6 0.8]
[0.   0.25 0.5  0.75 1.  ]
[ 1.          1.77827941  3.16227766  5.62341325 10.        ]


In [32]:
array5=np.zeros(4)
print(array5)

array6=np.zeros([3,3])
print(array6)

array7=np.diag([1,2,3,4])
print(array7)

array8=np.full((2,3),6)
print(array8)

[0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
[[6 6 6]
 [6 6 6]]


###ndarraty对象属性和数据转换###

In [33]:
warry=np.array([[1,2,3],[4,5,6]])
print(warry.ndim)
print(warry.shape)
print(warry.size)
warry.shape=3,2
print(warry)
print(warry.dtype)
print(warry.astype(np.float64).dtype)

2
(2, 3)
6
[[1 2]
 [3 4]
 [5 6]]
int32
float64


In [34]:
arr1=np.random.randint(100,200,size=(2,4))
print(arr1)
arr2=np.random.rand(5)
print(arr2)
arr3=np.random.rand(2,3)
print(arr3)

[[164 141 183 177]
 [198 117 182 158]]
[0.02524645 0.5490357  0.4904731  0.42531269 0.71607872]
[[0.93942735 0.33257343 0.99311875]
 [0.63139301 0.93556672 0.78085095]]


###数组变换####

In [35]:
arr1=np.arange(12)
print(arr1)
arr2=arr1.reshape(3,4)
print(arr2)
arr3=arr1.reshape(2,-1)#2行, arr1的行乘以列再除以2列
print(arr3)

arr4=arr2.ravel()
print(arr4)
arr5=arr2.flatten()
print(arr5)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [36]:
arr1=np.arange(6).reshape(3,2)
arr2=arr1*2
arr3=np.hstack((arr1,arr2))
print(arr3)#横向 = np.concatenate((arr1,arr2), axis=1)
arr4=np.vstack((arr1,arr2))
print(arr4)#纵向 = np.concatenate((arr1,arr2), axis=0)


[[ 0  1  0  2]
 [ 2  3  4  6]
 [ 4  5  8 10]]
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 0  2]
 [ 4  6]
 [ 8 10]]


In [37]:
arr=np.arange(16).reshape(4,4)
print(np.hsplit(arr,2))
print(np.vsplit(arr,2))

[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]
[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]


In [38]:
arr=np.arange(6).reshape(3,2)
print(arr.transpose((1,0)))
print(arr.T)

[[0 2 4]
 [1 3 5]]
[[0 2 4]
 [1 3 5]]


###切片和索引###

In [39]:
arr=np.arange(10)
print(arr)
print(arr[2])
print(arr[-1])
print(arr[1:4])
arr1=arr[1:4].copy()
print(arr1)

[0 1 2 3 4 5 6 7 8 9]
2
9
[1 2 3]
[1 2 3]


In [40]:
arr=np.arange(12).reshape(3,4)
print(arr)
print(arr[0,1:3])
print(arr[:2])
print(arr[(0,1),(1,3)])
print(arr[1:2],(0,2,3))
mask=np.array([1,0,1],dtype=bool)
print(arr[mask,1])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[1 2]
[[0 1 2 3]
 [4 5 6 7]]
[1 7]
[[4 5 6 7]] (0, 2, 3)
[1 9]


###数组的运算###

In [41]:
a=[1,2,3]
b=[]
for i in a:
    b.append(i*i)
print(b)
wy=np.array([1,2,3])
c=wy*2
print(c)

[1, 4, 9]
[2 4 6]


In [42]:
#ufunc函数
x=np.array([1,2,3])
y=np.array([4,5,66])
print(x+y)
print(x-y)
print(x*y)
print(x**y)
print(x>y)
print(x==y)

arr1=np.array([[0,0,0],[1,1,1],[2,2,2]])
arr2=np.array([1,2,3])
print(arr1+arr2)

arr1=np.array([1,3,5,7])
arr2=np.array([2,4,6,8])
cond=np.array([True,False,True,False])
result=[(x if c else y) for x,y,c in zip(arr1,arr2,cond)]
print(result)

[ 5  7 69]
[ -3  -3 -63]
[  4  10 198]
[         1         32 1165272329]
[False False False]
[False False False]
[[1 2 3]
 [2 3 4]
 [3 4 5]]
[1, 4, 5, 8]
